# Generated by Django 2.0.9 on 2019-07-14 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('jersey_number', models.IntegerField()),
                ('position', models.CharField(max_length=20, verbose_name=20)),
                ('height', models.CharField(max_length=14)),
                ('weight', models.IntegerField()),
                ('year_class', models.CharField(choices=[('FR.', 'FR.'), ('SO.', 'SO.'), ('JR.', 'JR.'), ('SR.', 'SR.')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('overall_wins', models.IntegerField()),
                ('overall_loses', models.IntegerField()),
                ('conference_wins', models.IntegerField()),
                ('conference_loses', models.IntegerField()),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('date', models.DateTimeField()),
                ('opponent', models.CharField(max_length=90)),
                ('location', models.TextField()),
                ('home_away', models.CharField(choices=[('HOME', 'HOME'), ('AWAY', 'AWAY'), ('TBD', 'TBD')], max_length=6)),
                ('win', models.BooleanField()),
                ('loss', models.BooleanField()),
                ('score', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=90)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('twitter_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='staffmember',
            name='team',
            field=models.ManyToManyField(to='main.Team'),
        ),
        migrations.AddField(
            model_name='seasonschedule',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Team'),
        ),
        migrations.AddField(
            model_name='roster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Team'),
        ),
        migrations.AddField(
            model_name='record',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='roster',
            field=models.ManyToManyField(to='main.Roster'),
        ),
    ]
