# Generated by Django 2.0.9 on 2019-07-29 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190717_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SeasonSchedule'),
        ),
        migrations.AddField(
            model_name='team',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seasonschedule',
            name='season',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
